services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    networks:
      - app
    environment:
      NODE_ENV: production
    restart: unless-stopped
networks:
  app: